### ISSUE TITLE
where is field for section.intro.headline

### ISSUE THREAD

**Issue by artisticdigital** [vojtasvoboda/oc-vega-theme#1]
The headline on the top image section, home page -
I'm seeing the call for the field data - 
/partials/sections/intro.htm being `<h1 class="block-title wow zoomIn">{{ 'section.intro.headline' | _ }}</h1>`

and I can find this data in the database - 
{"x":"section.intro.headline","en":"ONE PAGE BUSINESS THEME","cs":"ONE PAGE BUSINESS THEME","pl":"ONE PAGE BUSINESS THEME"}

but I just don't see where this field data is entered in the theme to modify it. I must just be missing something.

**Comment by artisticdigital** [comment]
A workaround (so client can modify it): 
Modified `<h1 class="block-title wow zoomIn">{{ 'section.intro.headline' | _ }}</h1>`
to `<h1 class="block-title wow zoomIn">{% content 'intro/headline' %}</h1>` and then just added a static piece of content in /content/intro/headline.htm - but would appreciate any insight.

**Comment by vojtasvoboda** [comment]
You can modify translations at the Backend > Settings > Translate > Translate messages where you can find section.intro.headline field.
